import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Codebolt docs — top-level sidebars.
 * See DOCUMENTATION_PLAN.md for the full structure and writing rules.
 */
const isDev = process.env.NODE_ENV === 'development';

const sidebars: SidebarsConfig = {
  getStartedSidebar: [{type: 'autogenerated', dirName: '01_get-started'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: '02_concepts'}],
  usingCodeboltSidebar: [{type: 'autogenerated', dirName: '02_using-codebolt'}],
  guidesSidebar: [{type: 'autogenerated', dirName: '03_guides'}],
  buildSidebar: [{type: 'autogenerated', dirName: '04_build-on-codebolt'}],
  // In dev the 05_reference files are excluded from the watcher, so the sidebar
  // must also be omitted — an autogenerated sidebar over an empty dir errors.
  ...(isDev ? {} : {
    referenceSidebar: [{type: 'autogenerated', dirName: '05_reference'}],
  }),
};

export default sidebars;
